version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: uglify-js
    versions:
    - 3.12.5
    - 3.12.6
    - 3.12.7
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
  - dependency-name: jsdom
    versions:
    - 16.5.0
    - 16.5.1
    - 16.5.2
    - 16.5.3
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.1
    - 5.27.1
    - 5.28.0
    - 5.30.0
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.8
  - dependency-name: yargs-parser
    versions:
    - 5.0.1
  - dependency-name: mocha
    versions:
    - 8.3.1
    - 8.3.2
  - dependency-name: jsonrepair
    versions:
    - 2.0.1
  - dependency-name: "@babel/register"
    versions:
    - 7.12.13
    - 7.13.8
  - dependency-name: vanilla-picker
    versions:
    - 2.11.2
  - dependency-name: source-map-loader
    versions:
    - 2.0.0
